from L import lengthOfLongestSubstring


if __name__ == '__main__':
    for i in range(10000):
        res = lengthOfLongestSubstring('tmmzuxtejihhhhhieeeergerhggggpweoifjjjjjjjjjjjjjjjjjjjjjjjjjjjieopqiojgirgergekjrojiiiiiiiiiiiiiiikjiojrigjeiorgjjjjjjjjjjjjjjjjjeiorgjpeoirjgeiorjgiehiowheogiwheoifewoifjpeoigrioenbvjneirhgw8ru98g3h4ugggreheuiiiiiijreogjpeoirjgwpeoirjgoeprjgijjjjjjjjjjjjjjjjjjjjjjjjgrioewpgjroeigjergopewjriigjvnnioerpjwgggggggggggggggrioewpgiorjegpoiwejrgi')
    print(res)
